name: Upload Python Package

on:
    push:
        branches:
            - 'dev*'
            - 'feature/**'

permissions:
  contents: read

jobs:
  deploy:
      runs-on: ubuntu-latest
      environment:
        name: test-pypi
        url: https://test.pypi.org/legacy/

      steps:
        - uses: actions/checkout@v3

        - name: Set up Python
          uses: actions/setup-python@v3
          with:
            python-version: '3.11'

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install build

        - name: Build package
          run: python -m build
            
        - name: Publish package
          uses: pypa/gh-action-pypi-publish@v1
          with:
            user: __token__
            password: ${{ secrets.TEST_PYPI_API_TOKEN }}